[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "EWx9TC7jrxX2BWLxrHrTYTzchuwcopFG98zAUohZqQUP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vboxuser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
