[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "4soi2JvwiLGNz4t1oXnWW5zcrwZ4LQSbFCpBfNubEjfK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vboxuser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
