[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cap_project = "aNRwZCzkCWyMtA25PKdqL4JVm3rpmw6CQJ7QjpPUWSL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vboxuser/Desktop/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
